---
- name: create wheel group
  ansible.builtin.group:
    name: wheel
    state: present

- name: Allow wheel group to have passwordless sudo
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: create user
  ansible.builtin.user:
    name: zhangtai
    groups: wheel
    append: true
    state: present
    shell: /bin/zsh
    create_home: yes
